<?php
// generated by Poedit from wpa9-gallery-cs_CZ.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=3; plural=(n==1 ? 0 : n>=2 && n<=4 ? 1 : 2);','language'=>'cs_CZ','pot-creation-date'=>'2026-05-28 10:29+0200','po-revision-date'=>'2026-05-28 10:34+0200','translation-revision-date'=>'2026-05-28 10:34+0200','project-id-version'=>'WPA9 Gallery','x-generator'=>'Poedit 3.9','messages'=>['← Back to album'=>'← Zpět na alba','%d photo'=>'%d fotografie' . "\0" . '%d fotografie' . "\0" . '%d fotografií','Photos by %s'=>'Fotografie %s']];
